### PR TITLE
vyatta-cfg-system: fix for unusable "link" option

### PR DESCRIPTION
**Pull request by zinrai**
In the inital state, the "link" option was not usable,
so I moved the "link" directory under "node.tag".
Aftewards, the "link" option became usable.

### CODE REVIEW

**Comment by dmbaturin** [comment]
Thanks! Now I wonder what was it doing inside the top level dir. ;)
Have you created a bug about it? Usually we include bug numbers in commit messages, although including it in the merge message can be an acceptable substitute.

**Comment by zinrai** [comment]
I just registered the bug on the forum : http://forum.vyos.net/showthread.php?tid=8507

**Comment by dmbaturin** [comment]
That's not where we keep bugs. ;)
http://bugzilla.vyos.net

**Comment by zinrai** [comment]
I just registered the bug on Bugzilla : http://bugzilla.vyos.net/show_bug.cgi?id=381

**Comment by dmbaturin** [comment]
Cool, thanks!

**Pull request merged**
