### PR TITLE
Add support for VXLAN

### PR DESCRIPTION
**Pull request by upa**
Pull request for CLI extension for kernel VXLAN interface.
Base codes are https://github.com/upa/vxlan-vyos .

For examples:
set interfaces vxlan vxlan0 vni 0
set interfaces vxlan vxlan 0 group 239.0.0.1
set interfaces vxlan vxlan0 address 10.0.0.1/24
or
set interfaces vxlan vxlan0 bridge-group bridge br0

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Hello Daniil and UnicronNL.

How do you think his great work? 
I think It is good idea to pull this request into helium branch .

He also filed on Bugzilla #294
http://bugzilla.vyos.net/show_bug.cgi?id=294.

**Comment by dmbaturin** [comment]
Sorry, guys, I'm still catching up after getting back home from a conference!
I'll pull the vxlan repo and try it out and merge soon.

**Comment by dmbaturin** [comment]
Ok, I've found some time to make the VXLAN package into a real debian package. :)
Merging to test how it will work together.

**Comment by dmbaturin** [comment]
Seems making it a separate package was a bad idea, so I decided to stick with the original UPA's idea to keep it in vyatta-cfg-system.
The build works now, and available for testins.

Also, note that policy/, ipv6/, and most of ip/ templates are autogenerated, there's no need to include them by hand.

**Comment by upa** [comment]
Thank you for merging and fixing autogenerated templates !!

**Comment by dmbaturin** [comment]
I should document the autogenerated templates part.

**Comment by dmbaturin** [comment]
Also, you should write a wiki page about VXLAN commands. :)

**Comment by upa** [comment]
Ok, I wrote a new wiki page for vxlan http://vyos.net/wiki/VXLAN .

**Comment by dmbaturin** [comment]
Cool, thanks!
By the way, maybe change "dev" to "link"? This is what we have in pseudo-ethernet now.

**Comment by upa** [comment]
Sure !!

**Pull request merged**
