### PR TITLE
vyatta-cfg-system: Bug #182 and #305

### PR DESCRIPTION
**Pull request by alexharpin**
vyatta-cfg-system: allow interfaces with dhcp addresses to be deleted

Update the checks in scripts/vyatta-address to allow the deletetion of
an interface that has a DHCP address.  The patch put in place for
Bug #259 (http://bugzilla.vyos.net/show_bug.cgi?id=259) checks that an
interface exists before preceding with the delete, but this chokes when
supplied with the address 'dhcp'.

This patch checks if the supplied interface is a DHCP address, before
extracting the IP address and then using that address for the check.

Bug #305 http://bugzilla.vyos.net/show_bug.cgi?id=305

vyatta-cfg-system: prevent dhcp updating dns when statically configured

When DNS settings are statically configured, prevent DHCP interfaces
from appending to resolv.conf with additional name servers.  If the
system has been configured with a static name server, just use that
instead of accepting ISP provided name servers.  These can be accepted
again by simply deleting the statically configured name servers.

Bug #182 http://bugzilla.vyos.net/show_bug.cgi?id=182

### CODE REVIEW

**Comment by alexharpin** [comment]
I only noticed Bug #305 when I was looking into Bug #182, mainly as I was taking the interface up and down on my test system and realised that the DHCP client wasn't being stopped on deletion and the interface was keeping it's IP address.  I debated with simply excluding DHCP addresses, but as the IP address is actually there, might as well make use of it.

**Comment by dmbaturin** [comment]
Config migration involves a lot of black magic. ;)
https://github.com/vyos/vyatta-config-migrate This package holds the scripts. 
It uses version files (like these ones: https://github.com/vyos/vyatta-cfg-system/tree/helium/cfg-version) and the version string in the config to determine if migration is needed. The framework for migration scripts is very annoying and brittle.

Perhaps it would be better to make it a separate option rather than a possible value of "name-server".

**Comment by alexharpin** [comment]
Cheers, can't believe I managed to look completely past that package, wood for the trees and all that!
I'll keep that one in mind for future, although I agree, it would probably be better to have it as an option instead of having it under name-server.

**Comment by dmbaturin** [comment]
Since VyConf (https://github.com/vyos/vyconfd/) config tree supports set/delete operations in exact same way as getting node contents, I think we should make the future migration mechanism do it that way. AST returned by the current XorpConfigParser doesn't support adding/deleting and rearranging nodes in arbitrary way so most of the time writing a migration script is all working around its limitations.

**Comment by alexharpin** [comment]
That sounds a very good idea, especially if it makes your life easier in the long run.  I was having a look at VyConf the other day, just need to stop finding things to fix so I can read through it properly :)

**Comment by dmbaturin** [comment]
If you write in python, it would be cool if you joined vyconf development. As you can see, the old code accumulated so much technical debt it's time to redesign it. :)

**Comment by alexharpin** [comment]
No problem, only too happy to help lend a hand.  I've got a few things I need to get off my plate first, but one I've cleared the decks I'll have a wade through and get myself acquainted with how it all hangs together.

**Pull request merged**
