### PR TITLE
T671: remove apparently unused scripts.

### PR DESCRIPTION
**Pull request by dmbaturin**
Please check if my garbage collection is not overly eager.

### CODE REVIEW

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
LGTM

**Comment by jestabro** [comment]
rl-system.init is called by vyos-router on boot (obscured by a loop that adds the suffix); I will have to look closely at the necessity of that script ...

**Comment by dmbaturin** [comment]
Interesting. Maybe we should have some policy against constructing executable paths on the fly in a way that makes them un-greppable.

**Comment by jestabro** [comment]
Yes, I trust that we would avoid that; when I first noticed it, I filed it as 'idiosyncratic behviour of legacy code'.

**Review by jestabro — APPROVED** [review]

**Pull request merged**
