### PR TITLE
Ethernet tso options

### PR DESCRIPTION
**Pull request by jhendryUK**
Expose some ethtool offload options in vbash cli to fix issue in bug:  http://bugzilla.vyos.net/show_bug.cgi?id=365

### CODE REVIEW

**Comment by dmbaturin** [comment]
Great, thanks!
The only thing: could you recreate the pull request against the newly created (and now default) lithium branch?
The point of that is that once we make a new release (helium = 1.1.x), we close its branch for new features, create a new branch, and continue development there, so if we need to make a maintenance release we just cherry-pick or add fixes to the old branch and make an image, and we can edit the new branch without fear of breaking anything.
In this case creating the new branch takes long because I'm the sole packager for the time being, other guys are even more busy than me. If you want to push something in other packages an notice that they lack the 'lithium' branch, please let me know and I'll create it there too.

**Comment by jhendryUK** [comment]
I see, that explains why I could not find the lithium branch for my forking...   No prob, I will re-create the pull request.

Also, if you have checked the code and are happy with it, I can assign the bug to myself to prevent anyone else from working on it.

**Comment by dmbaturin** [comment]
Assigning it to yourself can be a good idea. Even though we don't assign any formal meaning to it, people will know who's working on it.
Actually, at vyatta it didn't bear much formal meaning either and was mostly a way to say "I'm doing it" or "please do it".

**Comment by jhendryUK** [comment]
Understood,  I think I have managed to recreate the pull request properly.  Hope its right...

**Pull request closed without merging**
