### PR TITLE
Remove raid support

### PR DESCRIPTION
**Pull request by hydrajump**

### CODE REVIEW

**Comment by paulgear** [comment]
What is the value in removing RAID?  It effectively locks out people who want to run bare metal.

**Comment by hydrajump** [comment]
Hi @paulgear. The current RAID support doesn't provide the redundancy that you would expect from RAID-1. It uses ext2 and will actually fail during a power outage.

Why would it prevent you from installing VyOS on bare metal? The Ubiquiti EdgeMax products don't use RAID and that doesn't seem to be an issue in production environments.

**Comment by paulgear** [comment]
@hydrajump EdgeRouters are cheap enough devices that one can afford to have two of them in either hot or warm standby configurations, but on Intel bare metal servers, RAID 1 is a working minimum when deploying any server/router OS in production.

**Comment by dmbaturin** [comment]
@paulgear So you suggest to fix it instead of removing it?

**Comment by paulgear** [comment]
Are you guys suggesting that loss of power inevitably results in an unrecoverable system?  If so, I'll put my hand up to fix it (time permitting).  Even on ext2, that shouldn't be the result.

**Comment by dmbaturin** [comment]
ext2 is a truly terrible thing. The question is: why does it use ext2 with RAID? What could be the reason not to use a journaled FS such as ext3?

**Comment by paulgear** [comment]
I wasn't saying that ext2 should stay, I was saying that RAID-1 should stay. :-)

**Comment by hydrajump** [comment]
@paulgear I'm in the process of refactoring the install scripts, so I'll fire up a VM and see if I can figure out why `ext2` is being used and what I can do to fix it.

I would think that hardware RAID would be preferable over software RAID in a production environment, at least that has been the case in my experience. Anyway, if `mdadm` RAID-1 is important for VyOS I'll try to fix it. :wink:

**Comment by paulgear** [comment]
There are many advantages and disadvantages of both types of RAID. http://linux.yyz.us/why-software-raid.html  In my experience, the balance nearly always shifts in favour of software RAID on boxes doing routing & firewalling.

**Comment by hydrajump** [comment]
After further investigation it turns out that the RAID-1 mirroring is using `ext4` as set by `ROOT_FSTYPE`.

The reason I initially thought it was `ext2` is because that is what GRUB reports:

```
GRUB loading.
Welcome to GRUB!
(md0): Filesystem is ext2.
```

However, `sudo parted --script /dev/md0 print` reports:

```
Model: Linux Software RAID Array (md)
Disk /dev/md0: 4290MB
Sector size (logical/physical): 512B/512B
Partition Table: loop

Number    Start   End     Size    File system  Flags
1         0.00B  4290MB  4290MB  ext4
```

The GRUB version we are currently using is **1.98** and in newer versions GRUB would report `(md0): Filsystem is ext*` according to someone I chatted with on `#grub`, which wouldn't have been so misleading.

We'll keep RAID support, so I'm closing this pull request.

**Pull request closed without merging**
